### ISSUE TITLE
Crashes if number of sections = 0

### ISSUE THREAD

**Issue by dperetti** [TopicSo/RAMCollectionViewFlemishBondLayout#1]
Quick fix : in RAMCollectionViewFlemishBondLayout.m, line #421, add :

```
    if ( self.numberOfSections == 0 ) return 0;
```

This is because there is an assertion that [[self collectionView] numberOfItemsInSection:section] should not be called when there is no section at all.

**Comment by rais38** [comment]
@dperetti Thank you very much for your feedback.
