### ISSUE TITLE
Scrolling loose UI

### ISSUE THREAD

**Issue by MangeshVyas** [TopicSo/RAMCollectionViewFlemishBondLayout#2]
Thanks for this good component. But when I scroll this UI get disturb, I think due to index path, I add UIImage > pleasse check attached screen shot.

![screen shot 2014-03-08 at 6 59 16 pm](https://f.cloud.github.com/assets/2385660/2365428/abec5624-a6c5-11e3-8f06-406f4495ba15.png)

**Comment by rais38** [comment]
I can see that you have different width for highlighted cell and this isn't posible (just now). Highlighted cell must have same width although is possible change directions -`RAMCollectionViewFlemishBondLayoutGroupDirection`
